from typing import Any


class Mlx:
    SYNC_IMAGE_WRITABLE: int
    SYNC_WIN_FLUSH: int

    def mlx_init(self) -> Any: ...
    def mlx_new_window(
        self,
        mlx_ptr: Any,
        width: int,
        height: int,
        title: str,
    ) -> Any: ...
    def mlx_new_image(self, mlx_ptr: Any, width: int, height: int) -> Any: ...
    def mlx_get_data_addr(self, img_ptr: Any) -> tuple[memoryview, int, int, int]: ...
    def mlx_put_image_to_window(
        self,
        mlx_ptr: Any,
        win_ptr: Any,
        img_ptr: Any,
        x: int,
        y: int,
    ) -> int: ...
    def mlx_key_hook(self, win_ptr: Any, callback: Any, param: Any) -> int: ...
    def mlx_expose_hook(self, win_ptr: Any, callback: Any, param: Any) -> int: ...
    def mlx_loop_hook(self, mlx_ptr: Any, callback: Any, param: Any) -> int: ...
    def mlx_loop(self, mlx_ptr: Any) -> int: ...
    def mlx_loop_exit(self, mlx_ptr: Any) -> int: ...
    def mlx_destroy_image(self, mlx_ptr: Any, img_ptr: Any) -> int: ...
    def mlx_destroy_window(self, mlx_ptr: Any, win_ptr: Any) -> int: ...
    def mlx_sync(self, mlx_ptr: Any, sync_cmd: int, ptr: Any) -> int: ...
